name: Validate JSON Syntax

on: 
  pull_request:
    branches:
      - main

  merge_group: 
    branches:
     - main 

jobs:
  check-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Execute validation script
        run: node ./.github/workflows/utils/executeSyntaxValidation.js ./tokens.json

